# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='name',
            field=models.CharField(blank=True, default='Sat19Aug17_000348', max_length=80),
        ),
    ]
