# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythapp', '0003_auto_20170819_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='language',
            field=models.CharField(default='python', max_length=100),
        ),
        migrations.AlterField(
            model_name='bot',
            name='name',
            field=models.CharField(blank=True, default='Sat19Aug17_002005', max_length=80),
        ),
    ]
