# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 03:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pythapp', '0007_auto_20170819_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='botrel', to=settings.AUTH_USER_MODEL),
        ),
    ]
